name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        version: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: Check Moonbit Version
        run: |
          moon version --all

      - name: moon check
        run: moon check --deny-warn

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: moon test
        run: |
          moon test

      - name: moon bench
        run: |
          moon bench
